package hansol.xml2mermaid.output;

import hansol.xml2mermaid.model.FlowLink;
import hansol.xml2mermaid.model.FlowNode;
import hansol.xml2mermaid.model.Flowchart;
import java.util.HashMap;
import java.util.Map;

/** Flowchart -> Mermaid flowchart text (Mermaid 11.6 syntax). Shared by all output formats. */
public final class MermaidSyntax {
    private MermaidSyntax() {}

    public static String flowchart(Flowchart chart, OutputRequest r) {
        // Generated Mermaid IDs (N0, N1, ...) avoid reserved words such as "end".
        Map<String, String> ids = new HashMap<String, String>();
        StringBuilder out = new StringBuilder();
        out.append("%% Generated by HansolXmlToImage2 from ").append(singleLine(r.sourceName)).append('\n');
        out.append("flowchart ").append(r.direction).append('\n');
        for (FlowNode n : chart.nodes()) {
            String id = "N" + ids.size();
            ids.put(n.xmlId, id);
            String label = r.showId ? n.label + " [Id=" + n.xmlId + "]" : n.label;
            out.append("    ").append(id).append(n.shape.open)
               .append(escape(label)).append(n.shape.close).append('\n');
        }
        out.append('\n');
        for (FlowLink l : chart.links()) {
            out.append("    ").append(ids.get(l.from)).append(" -->");
            if (!l.label.isEmpty()) out.append("|\"").append(escape(l.label)).append("\"|");
            out.append(' ').append(ids.get(l.to)).append('\n');
        }
        return out.toString();
    }

    // Mermaid decimal entities protect quote/pipe/markup characters in labels.
    // Multiline XML labels are flattened to spaces for renderer compatibility.
    static String escape(String value) {
        StringBuilder s = new StringBuilder();
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            if (Character.isWhitespace(c) || Character.isISOControl(c)) s.append(' ');
            else if ("\"|<>&#`\\[]{}()".indexOf(c) >= 0) s.append('#').append((int) c).append(';');
            else s.append(c);
        }
        return s.toString();
    }

    /** Single-line text for Mermaid comments and Markdown headings. */
    static String singleLine(String value) {
        StringBuilder s = new StringBuilder();
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            s.append(Character.isISOControl(c) || c == '`' ? ' ' : c);
        }
        return s.toString();
    }
}
